---
name: configuration
brief: physical (dis)similarity and spatiotemporal connectedness
full: |
  CONFIGURATION conveys the quantity, spatiotemporal continuity, and physical
  similarity of the items named by the stem. Unlike [[Affiliation]], this
  category focuses on the physical variation of the items, rather than on
  variations of function or purpose. CONFIGURATION provides mass nouns for stems
  and works together with [[Perspective]] to communicate number. It communicates
  whether the members of a group are separate, touching, or fused together, and
  also provides a way of talking about questionable or borderline applications
  of the stem.
values:
  - abbrev: UNI
    name: Uniplex
    brief: individual instance
    full: TODO
  - abbrev: DUP
    name: Duplex
    brief: pair of instances
    full: TODO
  - abbrev: DCT
    name: Discrete
    brief: many similar instances
    full: TODO
  - abbrev: AGG
    name: aggregative
    brief: collection of dissimilar instances
    full: TODO
  - abbrev: SEG
    name: segmentative
    brief: close or contiguous group of similar instances
    full: TODO
  - abbrev: CPN
    name: componential
    brief: close or contiguous group of dissimilar instances
    full: TODO
  - abbrev: COH
    name: coherent
    brief: connected collection of similar instances
    full: TODO
  - abbrev: CST
    name: composite
    brief: connected collection of dissimilar instances
    full: TODO
  - abbrev: MLT
    name: multiform
    brief: borderline or questionable instance
    full: TODO
...
